### ISSUE TITLE
Broken pages in pdf file

### ISSUE THREAD

**Issue by markytaylor** [shloop/google-book-scraper#1]
Some pages are completely broken/pixels mangled strangely in PDF file. 
Using -k flag too keep images shows that they are downloaded just fine 

Example from URL: [Backpacker 16]( https://books.google.ro/books?id=beEDAAAAMBAJ&printsec=frontcover&rview=1&lr=#v=onepage&q&f=false)
![image](https://github.com/user-attachments/assets/bf505294-ced2-4f77-8c9b-b2d6cdd54316)
![image](https://github.com/user-attachments/assets/ac04c277-2dd1-49fe-8e14-822ec4138f20)

Downloaded images for **PA47, PA48, PA49**:
![00049-PA47](https://github.com/user-attachments/assets/81acd490-e668-4614-86e0-4b8dc1ed388b)
![00050-PA48](https://github.com/user-attachments/assets/47b3d9d2-88ac-4e91-a5de-1c2fbdeccc08)
![00051-PA49](https://github.com/user-attachments/assets/6e3b31c9-54cb-4783-8497-0442a1faa44a)

**Comment by shloop** [comment]
Nice catch. I saw this pattern before but didn't realize it was happening during PDF conversion. It looks like the images getting messed up are PNGs that are 8bpp whereas the JPGs and 24bpp PNGs are coming out fine. Should be an easy fix, at the cost of slightly larger output files. Good to know, since now I know *not* to try to optimize the images for newspapers to use a smaller color space.

**Comment by shloop** [comment]
Fixed in v0.3.1

**Comment by markytaylor** [comment]
Downloaded v0.3.1 and I confirm it works as it should. Good job !
