### ISSUE TITLE
Would you like to add staying logged in to Google Books using tokens?

### ISSUE THREAD

**Issue by NlckN4me** [shloop/google-book-scraper#6]
Would you like to add staying logged in to Google Books using tokens?

**Comment by shloop** [comment]
If I'm understanding correctly, what you're looking for is a way to download purchased content by using login information. From the testing I've done it looks like purchased books have to be read through Google _Play_ Books rather than Google Books, which would likely require an entire rewrite of the scraping logic. I can only see a _sample_ of content from purchased books in Google Books even though the book IDs are the same as they are on Google Play Books and I'm logged into an account that owns them. On the other side of things, although Google Play Books is able to view the publicly available books also available on Google Books it is **not** able to view its magazines or newspapers, which are really the main focus of this project. So in order to support purchased content, there would have to be entirely separate logic for scraping from Google Play Books rather than Google Books while still supporting both, and unfortunately I think that falls outside the scope of this project. I'm closing this as unplanned for now, but if I misunderstood your request please let me know!
